# Generated by Django 5.0.6 on 2024-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_views_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["product"],
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продукта",
            },
        ),
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(
                default=False, verbose_name="Признак текущей версия"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=150, verbose_name="Название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.CharField(max_length=50, verbose_name="Номер версии"),
        ),
    ]
